Repository ReverbTraining/ReverbRVA, pull requests merged in 2018-05, with the labels that each got.

#56 Things to do scott's addition
  scotts-addition/Things-to-do.md
Labels: Scott's Addition

#48 List of top 10 breweries
  scotts-addition/breweries.md
Labels: Scott's Addition

#57 Jackson Ward Bars & Restaurants
  jackson-ward/jackson-s-beer-garden.png
  jackson-ward/restabars.md
Labels: enhancement

#71 Jackson ward 64
  jackson-ward/images/jackson-beer-garden.png
  jackson-ward/restabars.md
Labels: bug

#75 The Fan - Index Fixes
  thefan/index.md
Labels: Fan

#79 Church Hill Index Fix
  church-hill/index.md
Labels: bug

#77 Updating header
  jackson-ward/restabars.md
Labels: enhancement
